export const choices = [
  { value: 'yes', label: 'Ja, meistens' },
  { value: 'partly', label: 'Mal so, mal so' },
  { value: 'no', label: 'Nein, das klappt noch nicht' },
  { value: 'unknown', label: 'Weiß ich nicht' },
  { value: 'na', label: 'Brauche ich gerade nicht' },
] as const;
export type Answer = typeof choices[number]['value'];
export type Question = { title: string; tip: string; action: string; check: string };
export type Topic = { id: string; title: string; invitation: string; intro: string; questions: Question[]; metric: string };
const q = (title: string, action: string, tip: string, check: string): Question => ({ title, action, tip, check });
export const topics: Topic[] = [
  { id: 'ordnung', title: 'Dateien & digitale Ordnung', invitation: 'Ich suche ständig Dateien und Unterlagen.', intro: 'Unterlagen finden und gemeinsam mit dem richtigen Stand arbeiten.', metric: 'Suchzeit: Miss bei fünf typischen Unterlagen die Minuten bis zum Fund. Wiederhole das nach zwei Wochen. Keine vertraulichen Dateinamen notieren.', questions: [
    q('Findest du wichtige Unterlagen an einem festen Ort?', 'Wähle für einen laufenden Auftrag einen gemeinsamen Ablageort. Verlinke vorhandene Dateien, statt sofort alles umzuziehen.', 'Zum Beispiel Angebote, Rechnungen und Projektunterlagen.', 'Findest du die Unterlagen für deinen ausgewählten Auftrag jetzt an einem festen Ort?'),
    q('Erkennst du eindeutig die aktuelle Version?', 'Fang mit einem einzigen Projekt an. Lege fest, welche Datei du weiterbearbeitest, und verschiebe ältere Kopien in einen Ordner „Archiv“. Lösche zunächst nichts. Wenn andere mitarbeiten, sag ihnen kurz, wo die aktuelle Datei liegt.', 'Auch dann, wenn mehrere Personen daran arbeiten.', 'Findest du beim nächsten Mal die richtige Datei, ohne mehrere Versionen öffnen zu müssen?'),
    q('Sind Zugriffsrechte nachvollziehbar vergeben?', 'Prüfe an einem Projekt, wer Zugriff braucht. Halte die zuständige Person fest und überprüfe unnötige Freigaben.', 'Nur die Personen, die diese Unterlagen benötigen.', 'Weißt du jetzt, wer die Unterlagen sehen und bearbeiten darf? Sind die Freigaben so eingestellt, wie ihr es vereinbart habt?'),
    q('Gibt es eine Sicherung, aus der du Dateien wiederherstellen kannst?', 'Kläre, welche Sicherung vorhanden ist. Teste mit einer unkritischen Testdatei die Wiederherstellung, bevor du dich darauf verlässt.', 'Eine synchronisierte Ablage allein beantwortet diese Frage noch nicht.', 'Konntest du die unkritische Testdatei aus der Sicherung wiederherstellen und öffnen?'),
    q('Gibt es eine Person, die die Ablage regelmäßig pflegt?', 'Lege eine verantwortliche Person und zehn Minuten pro Woche für neue Unterlagen fest.', 'Bei einem Einzelbetrieb kannst du das selbst sein.', 'Ist klar, wer sich um die Ablage kümmert? Sind die neuen Unterlagen beim nächsten vereinbarten Termin einsortiert?'),
  ]},
  { id: 'aufgaben', title: 'Termine & Aufgaben', invitation: 'Ich möchte weniger vergessen und besser planen.', intro: 'Wissen, was als Nächstes dran ist und wer sich kümmert.', metric: 'Überfällige Aufgaben: Zähle wöchentlich offene Aufgaben mit überschrittenem Termin. Betrachte zusätzlich, ob Termine realistisch gesetzt waren.', questions: [
    q('Stehen verbindliche Termine in einem verlässlichen Kalender?', 'Trage die Termine der nächsten Woche in deinen bestehenden Hauptkalender ein.', 'Private Details müssen dafür nicht mit dem Team geteilt werden.', 'Siehst du die verbindlichen Termine der nächsten Woche in deinem Hauptkalender?'),
    q('Haben offene Aufgaben einen festen Platz?', 'Sammle offene Aufgaben in einer einzigen Liste im vorhandenen Werkzeug.', 'Eine einfache Liste reicht für den Anfang.', 'Findest du deine offenen Aufgaben in einer Liste, ohne mehrere Stellen durchsuchen zu müssen?'),
    q('Ist für jede wichtige Aufgabe jemand verantwortlich?', 'Ergänze bei den fünf wichtigsten Aufgaben jeweils eine verantwortliche Person.', 'Auch bei Aufgaben, an denen mehrere Personen arbeiten.', 'Ist bei deinen fünf wichtigsten Aufgaben klar, wer sich jeweils darum kümmert?'),
    q('Ist bei wichtigen Aufgaben der nächste Schritt mit Termin klar?', 'Formuliere für drei offene Aufgaben den nächsten konkreten Schritt und einen realistischen Termin.', 'Zum Beispiel: Rückfrage am Dienstag beantworten.', 'Weißt du bei den drei ausgewählten Aufgaben, was als Nächstes passiert und bis wann?'),
    q('Prüfst du regelmäßig, was offen oder überfällig ist?', 'Reserviere einmal pro Woche 15 Minuten für deine Aufgabenübersicht.', 'So bleibt die Liste auch nach dem ersten Aufräumen hilfreich.', 'Hast du beim nächsten Wochencheck offene und überfällige Aufgaben gesehen und ihre nächsten Schritte geklärt?'),
  ]},
  { id: 'anfragen', title: 'Anfragen & Angebote', invitation: 'Ich verliere bei Anfragen und Angeboten den Überblick.', intro: 'Anfragen beantworten und offene Angebote im Blick behalten.', metric: 'Angebotsquote: Gewonnene Angebote geteilt durch alle entschiedenen Angebote desselben Zeitraums. Offene Angebote separat zählen; bei null Entscheidungen keine Quote berechnen.', questions: [
    q('Bekommst du bereits passende Kundenanfragen?', 'Kläre zuerst für eine Zielgruppe, welches konkrete Problem dein Angebot löst. Teste eine verständliche Angebotsbeschreibung in einem passenden Kanal.', 'Wenn noch keine Anfragen kommen, ist ein neues Verwaltungssystem meist nicht der erste Schritt.', 'Verstehen Menschen aus deiner Zielgruppe, wobei du ihnen hilfst? Halte nach deinem Test fest, ob daraus passende Rückfragen oder Anfragen entstanden sind.'),
    q('Sind deine offenen Anfragen an einem Ort sichtbar?', 'Fang mit deinen drei letzten Anfragen an: Was ist noch offen? Was ist der nächste Schritt? Halte das in einer einfachen Liste fest – möglichst dort, wo du schon arbeitest.', 'Unabhängig davon, ob sie per Telefon, E-Mail oder persönlich kommen.', 'Siehst du bei deinen drei letzten Anfragen auf einen Blick, was offen ist und was als Nächstes passiert?'),
    q('Erkennst du, welche Anfragen noch eine Antwort brauchen?', 'Kennzeichne neue, beantwortete und abgeschlossene Anfragen mit einem eindeutigen Status.', 'Ohne einzelne Postfächer oder Nachrichten durchsuchen zu müssen.', 'Erkennst du in deiner Übersicht direkt, welche Anfragen noch eine Antwort brauchen?'),
    q('Haben offene Angebote einen nächsten Schritt mit Datum?', 'Trage bei drei offenen Angeboten einen sinnvollen nächsten Kontakttermin ein.', 'Ein Termin zum Nachfassen sollte zur Absprache mit dem Kunden passen.', 'Haben deine drei ausgewählten Angebote jetzt einen passenden nächsten Kontakttermin?'),
    q('Hältst du fest, welche Angebote angenommen oder abgelehnt wurden?', 'Ergänze bei entschiedenen Angeboten das Ergebnis und, soweit bekannt, den Grund.', 'Ein noch offenes Angebot ist keine Absage.', 'Kannst du angenommene, abgelehnte und noch offene Angebote in deiner Liste auseinanderhalten?'),
  ]},
  { id: 'kennzahlen', title: 'Kennzahlen & Überblick', invitation: 'Ich möchte wissen, wie mein Geschäft läuft.', intro: 'Mit wenigen Zahlen bessere Entscheidungen treffen.', metric: 'Beginne mit einer Zahl für deine konkrete Entscheidung: etwa offene Angebote, überfällige Aufgaben oder gebuchte Stunden. Lege Zeitraum, Datenquelle und Zählregel fest. Umsatz ist nicht Gewinn und nicht Zahlungseingang.', questions: [
    q('Weißt du, welche Entscheidung deine Zahlen unterstützen sollen?', 'Schreibe eine konkrete Frage auf: zum Beispiel, ob genug Arbeit für den nächsten Monat beauftragt ist.', 'Erst die Frage, dann die passende Kennzahl.', 'Kannst du in einem Satz sagen, welche Entscheidung du mit der Zahl treffen möchtest?'),
    q('Sind die benötigten Daten schon verlässlich erfasst?', 'Prüfe fünf Einträge in deiner vorhandenen Quelle auf Vollständigkeit. Fehlende Werte als unbekannt markieren, nicht als null.', 'Zum Beispiel Angebotsstatus oder gebuchte Stunden.', 'Sind die fünf geprüften Einträge vollständig? Weißt du bei Lücken, was noch fehlt, ohne fehlende Werte als null zu zählen?'),
    q('Sind Zeitraum und Bedeutung deiner Kennzahlen klar?', 'Definiere für eine Kennzahl den Zeitraum und was genau gezählt wird.', 'Zum Beispiel entschiedene Angebote im Kalendermonat.', 'Ist schriftlich klar, was deine Kennzahl zählt und auf welchen Zeitraum sie sich bezieht?'),
    q('Kannst du die Zahlen ohne mehrfaches Abtippen zusammentragen?', 'Nutze zuerst einen vorhandenen Export oder eine einfache Tabelle. Prüfe Summen an wenigen bekannten Fällen.', 'Ein Dashboard lohnt sich erst mit einer verlässlichen Quelle.', 'Stimmen deine Stichproben mit der Übersicht überein, ohne dass du dieselben Zahlen mehrfach abtippen musst?'),
    q('Führt deine regelmäßige Auswertung zu einer konkreten Entscheidung?', 'Lege einen monatlichen Termin fest und notiere zu einer Zahl genau eine Maßnahme.', 'Eine Übersicht soll dir bei der Arbeit helfen.', 'Hast du beim nächsten Auswertungstermin eine konkrete Maßnahme und einen Termin dafür festgehalten?'),
  ]},
  { id: 'routinen', title: 'Wiederkehrende Arbeit & KI', invitation: 'Ich mache vieles immer wieder von Hand.', intro: 'Wiederholungen vereinfachen, ohne neue Fehlerquellen einzubauen.', metric: 'Zeitaufwand: Miss fünf Durchläufe vor und nach einer Änderung, einschließlich Kontrolle und Korrekturen. Eine Hochrechnung ist eine Schätzung, keine garantierte Ersparnis.', questions: [
    q('Kennst du eine häufige Aufgabe, die spürbar Zeit kostet?', 'Beobachte eine Woche lang wiederkehrende Arbeit. Notiere Häufigkeit und Zeitbedarf ohne sensible Inhalte.', 'Ohne wiederkehrenden Bedarf brauchst du keine Automatisierung.', 'Weißt du nach einer Woche, welche Aufgabe sich wie oft wiederholt und wie viel Zeit sie benötigt? Wenn sich nichts lohnt, brauchst du dafür keine Automatisierung.'),
    q('Ist der Ablauf dieser Aufgabe klar beschrieben?', 'Schreibe die einzelnen Schritte einer häufigen Aufgabe auf. Beginne mit einer Checkliste oder Vorlage.', 'Auch Ausnahmen und Entscheidungen gehören dazu.', 'Kannst du die Aufgabe mit deiner Checkliste durchgehen und erkennst du dabei auch die Ausnahmen?'),
    q('Sind die benötigten Eingaben verlässlich verfügbar?', 'Teste den Ablauf an fünf unkritischen Beispielen und notiere fehlende oder widersprüchliche Angaben.', 'Unklare Eingaben werden durch Automatisierung nicht automatisch besser.', 'Weißt du nach den fünf Testfällen, welche Eingaben fehlen oder widersprüchlich sind und vor dem nächsten Test geklärt werden müssen?'),
    q('Ist geklärt, welche Daten in den verwendeten Werkzeugen verarbeitet werden dürfen?', 'Kläre vor einem KI- oder Automatisierungstest die zulässigen Daten und Zugriffe. Verwende bis dahin erfundene Testdaten.', 'Keine Kundendaten, Zugangsdaten oder vertraulichen Texte für spontane Tests verwenden.', 'Ist für deinen Test geklärt, welche Daten du verwenden darfst und wer darauf zugreifen kann? Bis dahin bleibst du bei erfundenen Testdaten.'),
    q('Gibt es eine Kontrolle und einen manuellen Ersatzweg bei Fehlern?', 'Lege fest, wer Ergebnisse prüft und wie der Ablauf bei Fehlern manuell weitergeht.', 'Besonders vor dem Versand von Nachrichten oder Änderungen an Kundendaten.', 'Weißt du, wer das Ergebnis prüft und wie du bei einem Fehler manuell weiterarbeitest? Probiere das mit einem unkritischen Testfall aus.'),
  ]},
  { id: 'website', title: 'Website & Kontakt', invitation: 'Ich weiß nicht, ob meine Website Kunden bringt.', intro: 'Verstehen, ob Besucher dein Angebot und den nächsten Schritt erkennen.', metric: 'Passende Website-Anfragen: Frage neue Kontakte freiwillig, wie sie dich gefunden haben. Zähle wöchentlich passende Anfragen. Eine Conversion-Rate braucht zusätzlich verlässliche Besuchsdaten; ohne sie keine Prozentzahl ausweisen.', questions: [
    q('Ist auf deiner Website schnell erkennbar, wem du wobei hilfst?', 'Formuliere für die Startseite einen klaren Satz: Für wen bist du da und welches Problem löst du?', 'Bitte eine unbeteiligte Person, das Angebot nach kurzem Blick zu beschreiben.', 'Kann eine unbeteiligte Person nach einem kurzen Blick sagen, wem du wobei hilfst?'),
    q('Findet man auf dem Smartphone einfach den Kontakt?', 'Öffne die Seite auf deinem Handy und suche Telefonnummer oder Kontaktweg. Vereinfache den Weg, wenn du suchen musst.', 'Das ist eine Selbsteinschätzung, kein automatischer Website-Test.', 'Findest und erreichst du den Kontaktweg auf deinem Smartphone ohne langes Suchen?'),
    q('Zeigt die Website aktuelle und nachvollziehbare Arbeitsergebnisse?', 'Ergänze ein freigegebenes Projektbeispiel mit Ausgangslage, deiner Leistung und Ergebnis.', 'Verwende nur Inhalte, die du veröffentlichen darfst.', 'Kann ein Besucher an deinem Projektbeispiel erkennen, was die Aufgabe war, was du gemacht hast und was dabei herauskam?'),
    q('Hast du den Kontaktweg selbst erfolgreich ausprobiert?', 'Teste deinen Kontaktweg einmal vollständig und prüfe, ob die Nachricht wirklich ankommt.', 'Ein sichtbarer Formularbutton allein beweist noch keinen funktionierenden Versand.', 'Ist deine Testnachricht tatsächlich beim vorgesehenen Empfänger angekommen?'),
    q('Weißt du, ob über die Website passende Anfragen entstehen?', 'Frage bei den nächsten fünf Anfragen nach dem Kontaktweg und notiere, ob das Anliegen zu deinem Angebot passt.', 'Du musst dafür nicht sofort zusätzliche Besucheranalyse installieren.', 'Kannst du bei den nächsten fünf Anfragen festhalten, welche über die Website kamen und welche zu deinem Angebot passen? Unbekannte Kontaktwege bleiben als unbekannt markiert.'),
  ]},
];
export type Result = { kind: 'action' | 'clarify' | 'good' | 'irrelevant'; title: string; reason: string; steps: string[]; metric?: string };
export function evaluate(topic: Topic, answers: Answer[]): Result {
  if (answers.length !== topic.questions.length || answers.some(a => !choices.some(c => c.value === a))) throw new Error('Bitte alle Fragen beantworten.');
  const relevant = answers.filter(a => a !== 'na');
  if (!relevant.length) return { kind: 'irrelevant', title: 'Dieses Thema brauchst du gerade nicht.', reason: 'Du hast bei allen Fragen angegeben, dass du das gerade nicht brauchst.', steps: ['Du musst hier gerade nichts verändern. Schau bei Bedarf nach einem anderen Thema.'] };
  // Missing demand takes precedence over downstream implementation details.
  if ((topic.id === 'anfragen' || topic.id === 'routinen') && answers[0] !== 'yes' && answers[0] !== 'partly') {
    const no = answers[0] === 'no';
    return { kind: no ? 'action' : 'clarify', title: topic.id === 'anfragen' ? 'Zuerst den Bedarf an passenden Anfragen klären.' : 'Zuerst eine sinnvolle wiederkehrende Aufgabe finden.', reason: 'Bevor du einen Ablauf ausbaust, sollte klar sein, ob du ihn aktuell brauchst.', steps: [topic.questions[0].action, 'Für diesen Schritt ist kein neues Werkzeug nötig.'], metric: topic.questions[0].check };
  }
  const gaps = answers.map((a,i) => ({a,i})).filter(({a}) => a === 'no' || a === 'partly');
  // Clarify the KPI's purpose and source before building a dashboard.
  const unknown = answers.findIndex(a => a === 'unknown');
  if ((topic.id === 'kennzahlen' && unknown >= 0 && unknown < 2) || (!gaps.length && unknown >= 0)) return { kind: 'clarify', title: 'Schau dir diesen Punkt zuerst in Ruhe an.', reason: `Noch offen: ${topic.questions[unknown].title}`, steps: [topic.questions[unknown].action, 'Prüfe danach erneut, ob eine Änderung wirklich nötig ist.'], metric: topic.questions[unknown].check };
  if (!gaps.length) return { kind: 'good', title: 'Das scheint bei dir schon gut zu laufen.', reason: 'Bei den Punkten, die du brauchst, klappt es nach deinen Antworten meistens gut.', steps: ['Bleib bei dem, was für dich funktioniert. Deine Antworten geben keinen Anlass, dafür ein neues Programm einzuführen.'], metric: topic.metric };
  // Security/recovery prerequisites before convenience improvements.
  const prerequisite = (topic.id === 'ordnung' || topic.id === 'routinen') ? gaps.find(g => g.i === 3) : undefined;
  const ordered = prerequisite ? [prerequisite, ...gaps.filter(g => g !== prerequisite)] : gaps;
  if (topic.id === 'ordnung' && ordered[0].i === 1) return { kind: 'action', title: 'Welche Datei ist die aktuelle? Das sollte sofort klar sein.', reason: 'Deinen Antworten nach ist das nicht immer leicht zu erkennen. Fang mit einem einzigen Projekt an.', steps: ordered.slice(0,3).map(g => topic.questions[g.i].action), metric: topic.questions[ordered[0].i].check };
  return { kind: 'action', title: ordered[0].i === 3 && topic.id === 'ordnung' ? 'Kommst du im Notfall wieder an deine Dateien?' : topic.id === 'anfragen' && ordered[0].i === 1 ? 'Ein fester Platz für deine offenen Anfragen kann dir helfen.' : 'Hier kannst du anfangen.', reason: `Du hast bei „${topic.questions[ordered[0].i].title}“ „${choices.find(c => c.value === ordered[0].a)?.label}“ gewählt.`, steps: ordered.slice(0,3).map(g => topic.questions[g.i].action), metric: topic.questions[ordered[0].i].check };
}
export function summary(topic: Topic, answers: Answer[], result: Result): string {
  return ['JaMoKo Digital-Kompass', topic.title, '', 'Selbsteinschätzung, kein technischer Audit.', result.title, result.reason, '', 'Dein erster Schritt:', result.steps[0], ...(result.steps.length > 1 ? ['', 'Das kannst du später angehen:', ...result.steps.slice(1).map((s,i) => `${i+1}. ${s}`)] : []), ...(result.metric ? ['', 'Woran du merken kannst, ob es besser läuft:', result.metric] : []), '', 'Deine Antworten:', ...topic.questions.map((q,i) => `${q.title} — ${choices.find(c => c.value === answers[i])?.label ?? ''}`)].join('\n');
}
